<table>
 <tr align=left><td><img align=left src="https://i.creativecommons.org/l/by/4.0/88x31.png">
 <td>Text provided under a Creative Commons Attribution license, CC-BY. All code is made available under the FSF-approved MIT license. (c) Kyle T. Mandli</td>
</table>

In [1]:
from __future__ import print_function

# Review: Python

APMA 4300 Resources:
 - [Intro to Python](https://github.com/mandli/intro-numerical-methods/blob/master/01_intro_to_python.ipynb)
 - [Intro to NumPy](https://github.com/mandli/intro-numerical-methods/blob/master/02_NumPy.ipynb)
 - [Intro to Matplotlib](https://github.com/mandli/intro-numerical-methods/blob/master/03_matplotlib.ipynb)

Other resources:
 - [Basic Python](https://docs.python.org/2/tutorial/introduction.html)
 - [Software Carpentry - Programming in Python](http://swcarpentry.github.io/python-novice-inflammation/)
 - [NumPy Intro](http://mentat.za.net/numpy/intro/intro.html)
 - [Jessica Hamrick's nbgrader Intro](http://github.com/jhamrick/nbgrader-demo)

## Installation

There are two options this semester for getting the necessary software:
1. Install on your own machine
1. Use a cloud computing platform

### Your Own Machine

The easiest way to install all the components you will need for the class is to use the [Anaconda](http://anaconda.com/download) distribution.  We will be using python 3.x for all in class demos and homework so I strongly suggest you use the Python 3.6 version.

Alternatives to using Anaconda also exist in the form of Enthought's [Canopy](http://store.enthought.com/downloads/) distribution which provides all the tools you will need as well along with an IDE (development environment).

### Cloud Computing

Instead of running things locally on your machine there are a number of cloud services that you are welcome to use in order to get everything running easily.
 1. CoCalc - Create an account on [cocalc.com](https://www.cocalc.com) and interact with python via the provided terminal or Jupyter notebook inteface.
 
There are a number of other options now available but note that some will not have the required packages or may be otherwise incompatible:
 1. Azure Notebooks - Microsoft has free notebook hosting at http://notebooks.azure.com
 1. Google - Google has notebook hosting at http://colab.research.google.com/

## Basic Python

Python is a dynamic, interpreted language used throughout computational engineering and science.  Due to its ease of use, cost, and available tools we will be learning the material in this course using Python tools exclusively.  For those who are coming in without prior Python knowledge but a strong programming background this lecture should acquaint you with the basics.  For people who do not know Python and do not have a strong programming background it is strongly recommended that you take the time to look through the other tutorials mentioned above.

### Math

Basic math in Python is fairly straight forward with all the usual types of operations (`+`, `-`, `*`, `/`, `**`) which are addition, subtraction, multiplication, division and power.

In [2]:
1 / 2

0.5

Note that in Python 2 this would give you `floor(1 / 2) = 1`.

In [3]:
4 + 4**(3/2)

12.0

Python also understands imaginary numbers:

In [4]:
4 + 3j

(4+3j)

Some of the more advanced mathematical functions are stored in modules.  In order to use these functions we must first `import` them into our notebook and then use them.

In [5]:
import math

In [6]:
math?

In [7]:
math.sqrt(2.0)

1.4142135623730951

In [8]:
math.sin(math.pi / 2.0)

1.0

In [9]:
from math import *
sin(pi)

1.2246467991473532e-16

### Variables

Variables are defined and assigned to like many other languages.

In [10]:
num_students = 80
room_capacity = 85
(room_capacity - num_students) / room_capacity * 100.0

5.88235294117647

### Control Flow

`if` statements are the most basic unit of logic and allows us to conditionally operate on things.

In [11]:
x = 4
if x > 5:
    print("x is greater than 5")
elif x < 5:
    print("x is less than 5")
else:
    print("x is equal to 5")

x is less than 5


`for` allows us to repeat tasks over a range of values or objects.

In [12]:
for i in range(5):
    print(i)

0
1
2
3
4


In [13]:
for animal in ['cat', 'dog', 'chinchilla']:
    print(animal)

cat
dog
chinchilla


In [14]:
for n in range(2, 10):
    is_prime = True
    for x in range(2, n):
        if n % x == 0:
            print(n, 'equals', x, '*', n / x)
            is_prime = False
            break
    if is_prime:
        print("%s is a prime number" % (n))

2 is a prime number
3 is a prime number
4 equals 2 * 2.0
5 is a prime number
6 equals 2 * 3.0
7 is a prime number
8 equals 2 * 4.0
9 equals 3 * 3.0


### Functions

Functions are a fundamental way in any language to break up the code into pieces that can be isolated and repeatedly used based on their input.

In [15]:
def my_print_function(x):
    print(x)

my_print_function(3)

3


In [16]:
def my_add_function(a, b):
    return a + b, b

my_add_function(3.0, 5.0)

(8.0, 5.0)

In [17]:
def my_crazy_function(a, b, c=1.0):
    d = a + b**c
    return d

my_crazy_function(2.0, 3.0), my_crazy_function(2.0, 3.0, 2.0), my_crazy_function(2.0, 3.0, c=2.0)

(5.0, 11.0, 11.0)

In [18]:
def my_other_function(a, b, c=1.0):
    return a + b, a + b**c, a + b**(3.0 / 7.0)

my_other_function(2.0, 3.0, c=2.0)

(5.0, 11.0, 3.601328885557697)

In [19]:
def fibonacci(n):
    """Return a list of the Fibonacci sequence up to n"""
    values = [0, 1]
    while values[-1] <= n:
        values.append(values[-1] + values[-2])
        print(values)
    return values

fibonacci(100)
fibonacci?

[0, 1, 1]
[0, 1, 1, 2]
[0, 1, 1, 2, 3]
[0, 1, 1, 2, 3, 5]
[0, 1, 1, 2, 3, 5, 8]
[0, 1, 1, 2, 3, 5, 8, 13]
[0, 1, 1, 2, 3, 5, 8, 13, 21]
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55]
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144]


## NumPy

The most important part of NumPy is the specification of an array object called an `ndarray`.  This object as its name suggests stores array like information in multiple dimensions.  These objects allow a programmer to access the data in a multitude of different ways as well as create common types of arrays and operate on these arrays easily.

In [20]:
import numpy

### Constructors

Ways to make arrays in NumPy.

In [21]:
my_array = numpy.array([[1, 2], [3, 4]])
print(my_array)

[[1 2]
 [3 4]]


In [22]:
numpy.linspace(-1, 1, 10)

array([-1.        , -0.77777778, -0.55555556, -0.33333333, -0.11111111,
        0.11111111,  0.33333333,  0.55555556,  0.77777778,  1.        ])

In [23]:
numpy.zeros([3, 3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [24]:
numpy.ones([2, 3, 2])

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [25]:
numpy.empty([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

### Access

How do we access data in an array?

In [26]:
my_array[0, 1]

2

In [27]:
my_array[:,0]

array([1, 3])

In [28]:
my_vec = numpy.array([[1], [2]])
print(my_vec)

[[1]
 [2]]


In [29]:
numpy.dot(my_array, my_vec)
numpy.cross?

In [30]:
my_array * my_vec

array([[1, 2],
       [6, 8]])

### Manipulations

How do we manipulate arrays beyond indexing into them?

In [31]:
A = numpy.array([[1, 2, 3], [4, 5, 6]])
print("A Shape = ", A.shape)
print(A)

A Shape =  (2, 3)
[[1 2 3]
 [4 5 6]]


In [32]:
B = A.reshape((6,1))
print("A Shape = ", A.shape)
print("B Shape = ", B.shape)
print(B)

A Shape =  (2, 3)
B Shape =  (6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [33]:
numpy.tile(A, (2,2))

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [34]:
A.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [35]:
A = numpy.array([[1,2,3],[4,5,6],[7,8,9]])
print(A)
print(A.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [36]:
B = numpy.arange(1,10)
print(B)
print(B.reshape((3,3)))
C = B.reshape((3,3))

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [37]:
print(A * C)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [38]:
numpy.dot(A, C)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

### Mathematical Functions

In [39]:
x = numpy.linspace(-2.0 * numpy.pi, 2.0 * numpy.pi, 62)
y = numpy.sin(x)
print(y)

[ 2.44929360e-16  2.04552066e-01  4.00453906e-01  5.79421098e-01
  7.33885366e-01  8.57314628e-01  9.44489229e-01  9.91722674e-01
  9.97017526e-01  9.60149874e-01  8.82678798e-01  7.67880446e-01
  6.20609482e-01  4.47093793e-01  2.54671120e-01  5.14787548e-02
 -1.53890577e-01 -3.52752087e-01 -5.36696194e-01 -6.97944155e-01
 -8.29677014e-01 -9.26323968e-01 -9.83797952e-01 -9.99668468e-01
 -9.73264374e-01 -9.05702263e-01 -7.99839245e-01 -6.60152121e-01
 -4.92548068e-01 -3.04114832e-01 -1.02820997e-01  1.02820997e-01
  3.04114832e-01  4.92548068e-01  6.60152121e-01  7.99839245e-01
  9.05702263e-01  9.73264374e-01  9.99668468e-01  9.83797952e-01
  9.26323968e-01  8.29677014e-01  6.97944155e-01  5.36696194e-01
  3.52752087e-01  1.53890577e-01 -5.14787548e-02 -2.54671120e-01
 -4.47093793e-01 -6.20609482e-01 -7.67880446e-01 -8.82678798e-01
 -9.60149874e-01 -9.97017526e-01 -9.91722674e-01 -9.44489229e-01
 -8.57314628e-01 -7.33885366e-01 -5.79421098e-01 -4.00453906e-01
 -2.04552066e-01 -2.44929

In [40]:
x = numpy.linspace(-1, 1, 20)
numpy.sqrt(x)

C:\Users\anant\anaconda3\envs\mlgen\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in sqrt
  


array([       nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
       0.22941573, 0.39735971, 0.51298918, 0.60697698, 0.6882472 ,
       0.76088591, 0.82717019, 0.88852332, 0.9459053 , 1.        ])

In [41]:
x = numpy.linspace(-1, 1, 20, dtype=complex)
numpy.sqrt(x)

array([0.        +1.j        , 0.        +0.9459053j ,
       0.        +0.88852332j, 0.        +0.82717019j,
       0.        +0.76088591j, 0.        +0.6882472j ,
       0.        +0.60697698j, 0.        +0.51298918j,
       0.        +0.39735971j, 0.        +0.22941573j,
       0.22941573+0.j        , 0.39735971+0.j        ,
       0.51298918+0.j        , 0.60697698+0.j        ,
       0.6882472 +0.j        , 0.76088591+0.j        ,
       0.82717019+0.j        , 0.88852332+0.j        ,
       0.9459053 +0.j        , 1.        +0.j        ])

### Linear Algebra

Some functions for linear algebra available in NumPy.  Full implementation in `scipy.linalg`.

In [42]:
numpy.linalg.norm(x)

2.7144835701531846

In [43]:
M = numpy.array([[0,2],[8,0]])
b = numpy.array([1,2])
print(M)
print(b)

[[0 2]
 [8 0]]
[1 2]


In [44]:
x = numpy.linalg.solve(M,b)
print(x)

[0.25 0.5 ]


In [45]:
lamda, V = numpy.linalg.eig(M)
print(lamda)
print(V)

[ 4. -4.]
[[ 0.4472136  -0.4472136 ]
 [ 0.89442719  0.89442719]]


## SciPy

NumPy contains the basic building blocks for numerical computing where as the SciPy packages contain all the higher-level functionality.  Refer to the [SciPy webpage](http://www.scipy.org) for more information on what it contains.  There are also a number of [SciKits](http://scikits.appspot.com/scikits) which provide additional functionality

## Matplotlib

The most common facility for plotting with the Python numerical suite is to use the `matplotlib` package.  We will cover a few of the basic approaches to plotting figures.  If you are interested in learning more about `matplotlib` or are looking to see how you might create a particular plot check out the matplotlib [gallery](http://matplotlib.org/gallery) for inspiration.

Refer to the [APAM 4300 Notes](https://github.com/mandli/intro-numerical-methods/blob/master/03_matplotlib.ipynb) on matplotlib for detailed examples.

## Jupyter Notebooks

All class notes and assignments will be done within Jupyter notebooks (formally IPython notebooks).  It is important that you become acquainted with these as there are a couple of pitfalls that you should be aware of.
 - Before turning in an assignment make sure to go to the "Kernel" menu and restart the notebook.  After this select "Run All" from the "Cell" menu to rerun everything.  This will ensure that you have properly defined everything in your notebook and have not accidentally erased a variable definition.
 - Use version 4.0 of the notebook so as not to run into problems with deleting notebook cells.

## Debugging

(based on Jessica Hamrick's [debugging demo](https://github.com/jhamrick/nbgrader-demo))

Debugging is one of the most critical tools we have at our disposal.  Apart from standard inspection approaches (`print` statements) the Jupyter notebook has a number of ways to debug as well.

Jupyter notebooks provide an interface to the python debugger `pdb`.  The easiest way to use this functionality is by using the "magic" `%pdb` at the top of your notebook which will allow cause the notebook to jump into the python debugger anytime an exception is reached.  This will allow you to step through your code and figure out what is wrong.  If you want to step through code or just activate the trace back for the current cell use the `%debug` magic.

In [ ]:
# for inline plotting in the notebook
%matplotlib inline 

# debugger
%pdb

import numpy
import matplotlib.pyplot as plt

def plot_log():
    figure, axis = plt.subplots(2, 1)
    x = numpy.linspace(1, 2, 10)
    axis.plot(x, np.log(x)) # correct is plt.plot()
    plt.show()

plot_log()  # Call the function, generate plot

Automatic pdb calling has been turned ON


AttributeError: 'numpy.ndarray' object has no attribute 'plot'

> <ipython-input-46-f7becf422e8e>(13)plot_log()
     11     figure, axis = plt.subplots(2, 1)
     12     x = numpy.linspace(1, 2, 10)
---> 13     axis.plot(x, np.log(x)) # correct is plt.plot()
     14     plt.show()
     15 



Paths to debugging
1. Check the traceback
1. Use the `%debug` magic
1. `print` statements

and if all else fails
1. Copy and paste your error message into Google to see if anyone else has experienced similar problems. You'd be surprised how often this works!
2. Search [StackOverflow](https://stackoverflow.com/questions/tagged/python)
3. Consult fellow classmates
4. Consult the GSIs

## Code Styling

Very important in practice to write readable and understandable code.  Here are a few things to keep in mind while programming in and out of this class, we will work on this actively as the semester progresses as well.  The standard for which Python program are written to is called [PEP 8](http://www.python.org/dev/peps/pep-0008) and contains the following basic guidelines:
 - Use 4-space indentation, no tabs
 - Wrap lines that exceed 80 characters
 - Use judicious use of blank lines to separate out functions, classes, and larger blocks of contained code
 - Comment!  Also, put comments on their own line when possible
 - Use `docstrings` (function descriptions)
 - Use spaces around operators and after commas, `a = f(1, 2) + g(3, 4)`
 - Name your classes and functions consistently.
   - Use `CamelCase` for classes
   - Use `lower_case_with_underscores` for functions and variables
 - When in doubt be verbose with your comments and names of variables, functions, and classes
 
Good coding style will mean that we can more easily grade your assignments and understand what you are doing.  Please make sure to keep this in mind especially when naming variables, making comments, or documenting your functions.

## Last Notes

 - Live coding demos $\Rightarrow$ Bring your laptops to class.
 - All notebooks are found on [github](https://github.com/Hadrien-Montanelli/numerical-methods-pdes).
 - Highly recommend obtaining a github account if you do not already have one.  Will allow you start to become comfortable with `git`.
 - Also note that you can watch what changes were made and submit **issues** to the github project page if you find mistakes (PLEASE DO THIS!).